### ISSUE TITLE
-all_time doesn't seem to work if you already have a state_dir

### ISSUE THREAD

**Issue by pde** [SSLMate/certspotter#19] opened 2016-12-14 23:33 UTC
```
$ time echo .eff.org | certspotter  -verbose -all_time -watchlist -
certspotter: https://ct.googleapis.com/pilot: 2016/12/14 15:32:43 Existing log; scanning 0 new entries since previous scan (previous size 57152114, previous root hash = 589e0f0f727a5ad50455486294de8f2d7cbea90d449c75fddb19e147c1fbfad7)
certspotter: https://ct.googleapis.com/pilot: 2016/12/14 15:32:43 final log size = 57152114, final root hash = 589e0f0f727a5ad50455486294de8f2d7cbea90d449c75fddb19e147c1fbfad7
certspotter: https://ct.googleapis.com/aviator: 2016/12/14 15:32:44 Existing log; scanning 0 new entries since previous scan (previous size 46466472, previous root hash = 2dc19c651b26f8b1989ab9720b92d7855d53e8e0fc887e5d3656f4b04265f5b0)
certspotter: https://ct.googleapis.com/aviator: 2016/12/14 15:32:44 final log size = 46466472, final root hash = 2dc19c651b26f8b1989ab9720b92d7855d53e8e0fc887e5d3656f4b04265f5b0
certspotter: https://ct1.digicert-ct.com/log: 2016/12/14 15:32:44 Existing log; scanning 0 new entries since previous scan (previous size 733199, previous root hash = f2832e9a3e6e9f57c43d4ddfd2e6471d7d81628ce39aca0e449cf3cf2502056c)
certspotter: https://ct1.digicert-ct.com/log: 2016/12/14 15:32:44 final log size = 733199, final root hash = f2832e9a3e6e9f57c43d4ddfd2e6471d7d81628ce39aca0e449cf3cf2502056c
certspotter: https://ct.googleapis.com/rocketeer: 2016/12/14 15:32:45 Existing log; scanning 0 new entries since previous scan (previous size 56228621, previous root hash = 79e1617a93abcc084b763b6b39c62454df3007d9d6377003f4b17e2a663b75ba)
certspotter: https://ct.googleapis.com/rocketeer: 2016/12/14 15:32:45 final log size = 56228621, final root hash = 79e1617a93abcc084b763b6b39c62454df3007d9d6377003f4b17e2a663b75ba
certspotter: https://ct.ws.symantec.com: 2016/12/14 15:32:46 Existing log; scanning 0 new entries since previous scan (previous size 2082785, previous root hash = e4726fb167d714a1825ee4ba111292dd31684b26ab8ee238d18882b2e992552e)
certspotter: https://ct.ws.symantec.com: 2016/12/14 15:32:46 final log size = 2082785, final root hash = e4726fb167d714a1825ee4ba111292dd31684b26ab8ee238d18882b2e992552e
certspotter: https://ctlog.api.venafi.com: 2016/12/14 15:32:46 Existing log; scanning 0 new entries since previous scan (previous size 77525, previous root hash = 93f2bfd481e1b56c5291acb271780320d5b46f1c4750ec7a9ddced2ce8c0a9ea)
certspotter: https://ctlog.api.venafi.com: 2016/12/14 15:32:46 final log size = 77525, final root hash = 93f2bfd481e1b56c5291acb271780320d5b46f1c4750ec7a9ddced2ce8c0a9ea
certspotter: https://vega.ws.symantec.com: 2016/12/14 15:32:46 Existing log; scanning 0 new entries since previous scan (previous size 74616, previous root hash = 30c0e266b5ddb18d910e699c6c08ce526022c5e60fe2f9ebac814436c948da3d)
certspotter: https://vega.ws.symantec.com: 2016/12/14 15:32:46 final log size = 74616, final root hash = 30c0e266b5ddb18d910e699c6c08ce526022c5e60fe2f9ebac814436c948da3d
certspotter: https://ctserver.cnnic.cn: 2016/12/14 15:32:47 Existing log; scanning 0 new entries since previous scan (previous size 3558, previous root hash = 11629da08a9ec9724f3472e387866e04df6600177abbb2e08b2d690d0b34726a)
certspotter: https://ctserver.cnnic.cn: 2016/12/14 15:32:47 final log size = 3558, final root hash = 11629da08a9ec9724f3472e387866e04df6600177abbb2e08b2d690d0b34726a

real	0m4,346s
user	0m0,080s
sys	0m0,016s
```

Deleting `~/.certspotter` seems to fix this.

**Comment by AGWA** [comment] 2017-01-10 19:32
Dupe of #5, which is fixed in 31f2316aa2cdb56fc355f181f55da3e938fd9f55

**Closed by AGWA** 2017-01-10 19:32 UTC
